# Generated by Django 4.0.2 on 2024-05-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.package'),
        ),
    ]
