# Generated by Django 4.0.2 on 2024-05-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdetails',
            name='detail_message',
            field=models.IntegerField(default=0),
        ),
    ]
