# Generated by Django 4.0.2 on 2024-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_hiringdetails_detail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringdetails',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='detail_message',
            field=models.TextField(),
        ),
    ]
