# Generated by Django 4.0.2 on 2024-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_alter_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
