# Generated by Django 4.0.2 on 2024-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_package_status_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
